 char * mo_name[] = {
  "ZebOS",
 "bridge",
 "vpls",
 "mrib",
 "pim",
 "ntp",
 "vlan",
 "smtp",
 "rip",
 "bgp",
 "vr",
 "vrf",
 "mrib4Igmp",
 "ripng",
 "interface",
 "isis",
 "rib",
 "ospf6",
 "ospf",
 "pppoe",
 };
 
 
 char * module_xmlns_tb[] = {
  "http://www.ipinfusion.com/CMLSchema/None",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/None",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/None",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS",
 "http://www.ipinfusion.com/CMLSchema/ZebOS"
 }; 
